# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studCourse', '0002_auto_20190305_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='media_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='course/'),
            preserve_default=False,
        ),
    ]
