# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studCourse', '0003_document_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
    ]
