# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studCourse', '0004_remove_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='media_file',
            field=models.FileField(upload_to=''),
        ),
    ]
